BaseUrl= "/"
LanguageCode= "pt-BR"
DefaultContentLanguage = "pt-BR"
Title= "Jaydson Gomes"
paginate = 7
Copyright = "Creative Commons - 2017"
canonifyurls = true
theme= "paper"

[params]
  description = "Desenvolvimento de Software (JavaScript), devaneios e outras coisas"
  metadescription = "Desenvolvimento de Software (JavaScript), devaneios e outras coisas"
  cover = "images/2016/10/jaydson-header.jpg"
  author = "Jaydson Gomes"
  authorlocation = "Porto Alegre, Brasil"
  authorwebsite = "https://jaydson.com"
  bio= "Cofundador da @BrazilJS, Cofundador da @Nasc, Desenvolvedor de software, autor e editor no portal BrazilJS."
  logo = "images/2016/09/logo-jaydson-gray-1.png"
  paginate = 50
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..."
  githubName = "jaydson"
  twitterName = "jaydson"
  facebookName = "jaydson"
  instagramName = "jaydson"
  linkedinName = "jaydson"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [permalinks]
    post = "/:slug/"
  
  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"

  [params.social]
    twitter = "jaydson"

 [[menu.main]]
  name = "Blog"
  weight = -110
  identifier = "home"
  url = "https://jaydson.com"

[[menu.main]]
  name = "Palestras"
  weight = -100
  identifier = "palestras"
  url = "/palestras"